# Generated by Django 5.1.6 on 2025-03-03 12:26

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
